drop database if exists pediatria;
create database pediatria DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
use pediatria;
create table pacientes (
id_paciente int not null auto_increment primary key,
paciente_nombres varchar (64) not null,
paciente_paterno varchar (64) not null,
paciente_materno varchar (64) not null,
paciente_nacimiento date not null,
paciente_sexo varchar (64) not null,
paciente_peso double not null,
acompaniante_nombres varchar (64) null,
acompaniante_paterno varchar (64) null,
acompaniante_materno varchar (64) null,
acompaniante_relacion varchar (64) null,
acompaniante_correo varchar (64) null,
acompaniante_nacimiento date null,
acompaniante_celular varchar (16) null,
acompaniante_casa varchar (16) null,
acompaniante_oficina varchar (16) null,
acompaniante_direccion varchar (128) null,
acompaniante_estado varchar (16) null,
acompaniante_notas varchar (256) null,
acompaniante_ocupacion varchar (32) null,
antecedentes_importantes varchar (4096) null,
alergias varchar (4096) null,
quien_refiere_al_paciente varchar (64) null,
motivo_consulta varchar (4096) null,
observaciones varchar (4096) null,
nacimiento_por varchar (64) null,
numero_embarazo int (1) null,
peso_nacer double null,
semanas_gestacion int (3) null,
apgar int (1) null,
lactancia varchar (32) null,
talla_nacer double null,
perimetro_cefalico double null,
alimentos_solidos boolean null,
tamiz_metabolico boolean null,
tamiz_cardiologico boolean null,
hospitalizado_nacer boolean null,
tamiz_auditivo boolean null,
hijos_fallecidos boolean null,
gestaciones boolean null,
diabetes boolean null,
cancer boolean null,
tuberculosis boolean null,
hipertension boolean null,
convulsiones boolean null,
enfermedad_sangre boolean null,
ingesta_medicamentos boolean null,
cirugias boolean null,
transfusiones boolean null,
enfermedades_importantes varchar (4096) null,
denticion boolean null,
realiza_ejercicio boolean null,
desarrollo_psicomotriz boolean null,
interrogatorio varchar (4096) null,
bcg date null,
hepatitis_a1 date null,
hepatitis_a2 date null,
hepatitis_b1 date null,
hepatitis_b2 date null,
hepatitis_b3 date null,
pentavalente_1 date null,
pentavalente_2 date null,
pentavalente_3 date null,
dpt date null,
rotavirus_1 date null,
rotavirus_2 date null,
rotavirus_3 date null,
neumococica_1 date null,
neumococica_2 date null,
neumococica_3 date null,
neumococica_4 date null,
meningococo_1 date null,
meningococo_2 date null,
varicela_1 date null,
varicela_2 date null,
influenza_1 date null,
influenza_2 date null,
refuerzo_influenza date null,
srp_1 date null,
srp_2 date null,
sabin date null,
tdap date null,
sarampion date null,
vph date null,
otras varchar (4096) null
);

create table consultas(
id_consulta int not null primary key auto_increment,
padecimiento_actual varchar (4096) not null,
fecha_inicio date not null,
altura double not null,
peso double not null,
fc double not null,
fr double not null,
imc double not null,
diagnosticos varchar (4096) not null,
medicamentos varchar (4096) not null,
indicaciones varchar (4096) not null,
fecha_consulta date not null,
id_paciente int not null,
foreign key consultas (id_paciente) references pacientes (id_paciente)
);

insert into pacientes (paciente_nombres, paciente_paterno, paciente_materno, paciente_nacimiento, paciente_sexo, paciente_peso, acompaniante_nombres, 
acompaniante_paterno, acompaniante_materno, acompaniante_relacion, acompaniante_correo, acompaniante_nacimiento, acompaniante_celular, 
acompaniante_casa, acompaniante_oficina, acompaniante_direccion, acompaniante_estado, acompaniante_notas, acompaniante_ocupacion, 
antecedentes_importantes, alergias, quien_refiere_al_paciente, motivo_consulta, observaciones, nacimiento_por, numero_embarazo, peso_nacer, 
semanas_gestacion, apgar, lactancia, talla_nacer, perimetro_cefalico, alimentos_solidos, tamiz_metabolico, tamiz_cardiologico, hospitalizado_nacer, 
tamiz_auditivo, hijos_fallecidos, gestaciones, diabetes, cancer, tuberculosis, hipertension, convulsiones, enfermedad_sangre, ingesta_medicamentos, 
cirugias, transfusiones, enfermedades_importantes, denticion, realiza_ejercicio, desarrollo_psicomotriz, interrogatorio) 
VALUES ('Samuel','González','Espinoza','1998/07/03','Masculino', '155', 'Roberto Antonio', 'Herrera', 'Monzón', 'Hermano', 'roberto_herrera@gmail.com', 
'1923/02/15', '6805-2351', '2443-0983', '2451-0451', 'Altos del Palmar, colonia San Luis, Pasaje F #6', 'Divorciado', 'Estas son las notas del acompañante', 
'Maestro de obras', 'Van los antecedentes importantes', 'Alergia al trabajo y a los lunes', 'Lo refiere el tio', 'El motivo es que se sentia mal', 
'Ha bajado de peso y tiene sintomas mero raros', 'Parto natural', '2', '315.23', '17', '3', 'Pecho', '28.78', '102.59', '1', '1', '1', '1', '1', '1', 
'1', '1', '1', '1', '1', '1', '1', '1', '1', '1', 'Ya le ha dado hepatitis al bro', '1', '1', '1', 'Pos este es el interrogatorio');

create table usuarios(
id_usuario int not null auto_increment primary key,
usuario varchar (32) not null,
clave varchar (64) not null,
tipo int (1) not null
);

insert into usuarios (usuario, clave, tipo) values ('admin', 'admin', '1');
insert into usuarios (usuario, clave, tipo) values ('user', 'user', '2');
select * from consultas;
select count(fecha_inicio) from consultas where fecha_inicio='2020-05-01';